version: '3.1'

services:

  persona_db:
    image: postgres
    #build: .
    container_name: persona_db
    # restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: persona
    ports:
      - 5432:5432
