# Generated by Django 4.0.1 on 2022-01-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='myapp/personas/fotos', verbose_name='Foto')),
                ('documento', models.FileField(blank=True, null=True, upload_to='myapp/personal/documentos/', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
            },
        ),
    ]
